### ISSUE TITLE
Remove obsolete parameter "limitsAtInit"

### ISSUE THREAD

**Issue by dietmarw** [modelica/ModelicaStandardLibrary#2590] opened 2018-06-05 15:34 UTC
During work on #2561 it was noticed that some blocks still contain the obsolete parameter `limitsAtInit` which can be removed in the next MAJOR version. See also 
153352f08676b88dd9c845fa02157a24a2bc5711 for some additional info on this.

**Comment by beutlich** [comment] 2018-10-26 06:55
Duplicate of #2226.

**Closed by beutlich** 2018-10-26 06:55 UTC
Labels: L: Blocks, duplicate, task

**Comment by thorade** [comment] 2019-08-15 11:15
@beutlich 
https://help.github.com/en/articles/about-duplicate-issues-and-pull-requests
Duplicate of #2226

**Comment by beutlich** [comment] 2019-08-15 11:17
I did so at 2018-10-26.

**Comment by thorade** [comment] 2019-08-15 11:19
You marked it manually, and now you also used github special syntax to mark it as duplicate
