### ISSUE TITLE
Modelica.Fluid.Examples.HeatingSystem generating Warnings in Dymola

### ISSUE THREAD

**Issue by markusandres3DS** [modelica/ModelicaStandardLibrary#2515] opened 2018-04-26 11:32 UTC
Simulating the default version of the example gives quite some warnings that should not pop up in the MSL. These are:
- Incompatible units.
- Unable to differentiate equations for variables having stateSelect = StateSelect.prefer.
- Conflicting start values

**Comment by beutlich** [comment] 2018-04-26 11:39
See also #2370.

**Comment by beutlich** [comment] 2018-04-26 11:45
@markusandres3DS Did you test with MSL v3.2.2 or the current master?

**Comment by markusandres3DS** [comment] 2018-04-26 11:47
I used MSL v3.2.2

**Comment by beutlich** [comment] 2018-04-26 11:48
> I used MSL v3.2.2

Can you please reproduce in current master MSL (which is 989 commits ahead of MSL v3.2.2). Thank you.

**Comment by beutlich** [comment] 2018-04-26 11:59
As far as the units concerned, this is a duplicate of #1995.

**Comment by HansOlsson** [comment] 2018-04-26 12:24
> Can you please reproduce in current master MSL (which is 989 commits ahead of MSL v3.2.2). Thank you.

Apart from the unit-issue they can be reproduced. 
And #1995 is still open since the change causes division by zero if homotopy is activated, which is a regression.

**Comment by HansOlsson** [comment] 2018-05-07 15:11
Note that "Unable to differentiate equations for variables having stateSelect = StateSelect.prefer." also occur for Modelica.Fluid.Examples.InverseParameterization (which also uses the ControlledPump), but not for ModelicaTest.Fluid.TestComponents.Machines.TestControlledPump

**Comment by casella** [comment] 2018-05-29 11:10
With the current development version of 3.2.3, the only remaining warning is about der(tank.V) having a zero start attribute. Unfortunately, there's nothing I can do about that, because it is not possible to directly set such a start attribute. Besides, having zero in this case is just fine.

**Closed by casella** 2018-05-29 11:10 UTC
Labels: L: Fluid, example
