### ISSUE TITLE
Uppercase first letter for fullrobot and oneAxis

### ISSUE THREAD

**Issue by hyumo** [modelica/ModelicaStandardLibrary#3023] opened 2019-07-03 18:10 UTC
According to `Modelica.UsersGuide.Conventions.ModelicaCode.Naming`, 
```
Class names start always with an upper case letter, with the exception of functions, that start with a lower case letter.
```
The following classes are not following this rule:
-`Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.oneAxis`
-`Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.fullRobot`

It might be good to fix them in MSL 4.0 when backward compatibility could be ignored.

**Comment by beutlich** [comment] 2019-07-13 19:11
This actually is a duplicate of #2431, but I'll care for it separately by #3041, such that #2431 can deal with the remaining renaming issues (of underscores in non-example class names).

> It might be good to fix them in MSL 4.0 when backward compatibility could be ignored.

Backwards-ompatibility is never an issue for example models.

**Closed** 2019-07-23 17:11 UTC
Labels: L: Mechanics.MultiBody, example, task
