### ISSUE TITLE
Double inheritance of PartialModelicaServices.Animation.PartialShape by Visualizers.Advanced.Shape

### ISSUE THREAD

**Issue by dariomangoni** [modelica/ModelicaStandardLibrary#3765] opened 2021-03-04 20:54 UTC
I don't know if it is intended but the `Modelica.Mechanics.MultiBody.Visualizers.Advanced.Shape` class extends from:
- `ModelicaServices.Animation.Shape`, that extends from:
  + **`Modelica.Utilities.Internal.PartialModelicaServices.Animation.PartialShape`**
- **`Modelica.Utilities.Internal.PartialModelicaServices.Animation.PartialShape`**

Thus making **`PartialShape`** inherited twice.

**Comment by beutlich** [comment] 2021-03-04 22:41
Duplicate of #845. Tools are free to adapt ModelicaServices though.

**Closed by beutlich** 2021-03-04 22:41 UTC
