### ISSUE TITLE
Model with connectors having a zero-sized placement transformation extent

### ISSUE THREAD

**Issue by svorkoetter** [modelica/ModelicaStandardLibrary#2630] opened 2018-06-13 15:25 UTC
The model `Modelica.Blocks.Examples.NoiseExamples.Utilities.Parts.MotorWithCurrentControl` has two connectors, `phi_motor` and `w`, which have the following declarations and annotations:

https://github.com/modelica/ModelicaStandardLibrary/blob/e935b645633bd0579a8281d99fe02ef15f9db096/Modelica/Blocks/package.mo#L2287-L2293

Notice that the `Placement.iconTransformation.extent` of both of these is zero sized, although a specific location is specified (i.e. it's not `{{0,0},{0,0}}`. This leads me to suspect that this was not intentional.

The issue originated in 3.2.2, but just came to my attention while reviewing 3.2.3.

**Comment by beutlich** [comment] 2018-06-13 18:09
According to 679eaff77cbb841ecf40234e9ff979e1cb0d6fa9 @tobolar should know.

**Comment by tobolar** [comment] 2018-06-14 11:13
The two variables of noiseless _phi_motor_ and _w_ could be of interest for e.g. post-processing but should not be accessible/connected from outside when instantiated. That's why they are disabled in the motor's icon.

**Comment by beutlich** [comment] 2018-06-14 11:28
Oops, duplicate of #2313.

**Closed by beutlich** 2018-06-14 11:28 UTC
Labels: L: Blocks, V: 3.2.2, duplicate

**Comment by dietmarw** [comment] 2018-06-14 14:04
So why not simply remove all graphical annotations from that connector? That should work right?

**Comment by svorkoetter** [comment] 2018-06-14 14:06
That was my thought too, but apparently the connector _is_ supposed to be displayed in the diagram layer.

**Comment by dietmarw** [comment] 2018-06-14 14:19
But both are accessible:
 * `phi_motor` via `angleSensor.phi`
 * `w` via `speedSensor.w`
So I don't understand why one would need the additional connectors.

**Comment by svorkoetter** [comment] 2018-06-14 14:31
Agreed. The connectors serve no purpose other than to expose corner cases of the specification and thus make the model non-portable between tools.

**Comment by tobolar** [comment] 2018-06-14 14:31
Disabling graphical annotations has a drawbeck of mixing graphical and textual modelling.

I'm not the author but can imagine the motivation to have phi_motor and w was fast localization in a variable browser (post-processing). But apparently this is not utilized in the example `Modelica.Blocks.Examples.NoiseExamples.ActuatorWithNoise`, so could be deleted as well.
