### ISSUE TITLE
Recompilation of binaries necessary

### ISSUE THREAD

**Issue by MatthiasBSchaefer** [modelica/ModelicaStandardLibrary#4178] opened 2023-08-10 06:06 UTC
In the master branch e.g. commit ce36c07 examples which include a CombiTimeTable are not compiling, because the function
ModelicaStandardTables_CombiTimeTable_init3
can not be found in the binaries. The function was added to ModelicaStandardTables.c after the last built of the binaries. 
So a recompilation of the binaries for all platforms is necessary.

**Comment by beutlich** [comment] 2023-08-10 06:17
I know, this is done (usually by me) just before a new release of the MSL is tagged.

**Comment by beutlich** [comment] 2023-08-10 06:20
Duplicate of #3911.

**Comment by beutlich** [comment] 2023-08-10 06:31
I am actually waiting for #4047 to get merged first. ⏳

**Comment by beutlich** [comment] 2023-08-10 18:32
Meanwhile you can find the updated Windows binaries in https://github.com/beutlich/ModelicaStandardLibrary/tree/update-binaries.

**Comment by MatthiasBSchaefer** [comment] 2023-08-11 05:37
Thank you !

**Comment by beutlich** [comment] 2024-03-13 18:12
Resolved by #4250.

**Closed by beutlich** 2024-03-13 18:12 UTC
Labels: duplicate, L: Resources, V: 4.1.0-dev
