### ISSUE TITLE
FluidHeatFlow.Sources.IdealPump: equations have a flaw

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaStandardLibrary#2549] opened 2018-05-26 04:28 UTC
The dependency of pressure increase versus volumeFlow is (according to Euler) linear without the abs around volumeFlow.
To get volumeFlow negative, the pressure increase has to get higher than at zero flow.

**Comment by beutlich** [comment] 2018-08-05 18:00
Reopen, since the fix in b7a64818aba4bf6375ba013b18b5afa2daa439d1was later reverted by dfa793f45a695f8e409d08a08b4f047d068566ec. Issue will be closed automatically once #2688 gets merged.

**Comment by beutlich** [comment] 2018-08-05 18:14
Removed the `V: 3.2.2` label since the issue is present since 60f640b170704a713dfb1d05137f3894e03def43 (MSL v2.2.1) where IdealPump was added.

**Closed** 2018-08-06 08:11 UTC
Labels: L: Thermal.FluidHeatFlow, bug
