### ISSUE TITLE
Questionable reference result for Modelica.Electrical.Analog.Examples.OpAmps.DifferentialAmplifier

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaStandardLibrary#3518] opened 2020-03-20 16:20 UTC
In the [reference results](https://github.com/modelica/MAP-LIB_ReferenceResults/blob/v4.0.0-beta.2/Modelica/Electrical/Analog/Examples/OpAmps/DifferentialAmplifier/DifferentialAmplifier.csv#L3769) for the `Modelica.Electrical.Analog.Examples.OpAmps.DifferentialAmplifier`, at time `0.18945` there is a really odd jump in the `opAmp.v_out` variable:

![DifferentialAmplifier](https://user-images.githubusercontent.com/329963/77183490-b32b7b80-6ace-11ea-918b-22da1a52876c.png)

SystemModeler doesn't reproduce this, and it seems incorrect.

**Comment by AHaumer** [comment] 2020-03-20 18:40
I can't reproduce that odd jump with Dymola 2020 and tolerance 1e-6. 
Maybe the reference result was taken before we changed the tolerance?

**Comment by beutlich** [comment] 2020-03-20 19:29
It is reproducible with tolerance=1e-7.

```
simulateModel(
  problem="Modelica.Electrical.Analog.Examples.OpAmps.DifferentialAmplifier",
  startTime=0,
  stopTime=0.2,
  outputInterval=5e-05,
  method="Dassl",
  tolerance=1e-07,
  resultFile="DifferentialAmplifier");
```

**Comment by beutlich** [comment] 2020-03-21 12:48
I uploaded the new reference file by https://github.com/modelica/MAP-LIB_ReferenceResults/commit/432e32b53c612c5d8448c50516afab67312507b6

Still, I want to keep this issue open as a reminder for @HansOlsson to analyze the solver issue.

![grafik](https://user-images.githubusercontent.com/14896695/77226696-9c426300-6b7a-11ea-872d-cacb818c64fa.png)

**Comment by maltelenz** [comment] 2020-03-23 08:35
SystemModeler passes correctness against the updated reference results, thank you @beutlich.

**Comment by beutlich** [comment] 2020-03-23 08:40
Thanks for confirmatio. Still a workaround only, since those updated ref results have to created manually.

**Comment by beutlich** [comment] 2020-04-27 14:21
> Still, I want to keep this issue open as a reminder for @HansOlsson to analyze the solver issue.

Closing as tool-issue, finally.

**Closed by beutlich** 2020-04-27 14:21 UTC
Labels: L: Electrical.Analog, V: 4.0.0-dev, tool-issue
