### ISSUE TITLE
Modelica.Blocks.Logical.Hysteresis: Wrong descriptions of parameter uLow and uHigh

### ISSUE THREAD

**Issue by PMehrfeld** [modelica/ModelicaStandardLibrary#3571] opened 2020-06-03 13:33 UTC
The description of `uLow` says:  

> if y=true and u<=uLow, switch to y=false

However, the following minimal example shows that `u` needs to be `<uLow`.

The same is valid for `uHigh`. It is not greater equal, but only greater. Change for example the amplitude of the `Pulse` to 0.5.

```Modelica
model TestHyst
  Modelica.Blocks.Logical.Hysteresis hysteresis(uLow=0, uHigh=0.5) annotation (Placement(transformation(extent={{-12,-10},{8,10}})));
  Modelica.Blocks.Sources.Pulse pulse(period=0.3, startTime=0.1) annotation (Placement(transformation(extent={{-88,-10},{-68,10}})));
equation 
  connect(pulse.y, hysteresis.u) annotation (Line(points={{-67,0},{-14,0}}, color={0,0,127}));
  annotation (uses(Modelica(version="3.2.3")));
end TestHyst;
```

**Solution**  
Either change parameter descriptions or code.

**Comment by beutlich** [comment] 2020-06-03 15:32
Already fixed for v4.0.0. Duplicate of #2802. https://github.com/modelica/ModelicaStandardLibrary/blob/25cc814816b4d7b26e886894a053d5d8dfaf8656/Modelica/Blocks/Logical.mo#L511-L512

**Closed by beutlich** 2020-06-03 15:32 UTC
Labels: L: Blocks, duplicate
