### ISSUE TITLE
Modelica icon color

### ISSUE THREAD

**Issue by DagBruck** [modelica/ModelicaStandardLibrary#3567] opened 2020-05-27 13:40 UTC
The Modelica library icon layer has a red dot, but the red color was changed in the recent update of the official Modelica icons. The color of the icon is now RGB(200, 16, 46).

**Comment by dietmarw** [comment] 2020-05-27 15:17
We had discussed the change of the icon in #3388 and decided to not change it. 
So this would be a duplicate of that I guess.

**Comment by DagBruck** [comment] 2020-05-27 15:54
Well, the discussion in #3388 (with regards to color) was primarily about the grey color of the "m", and people thought the black "m" was better. I don't think there was any decision about the red dot.

**Closed** 2024-03-12 14:42 UTC
Labels: P: trivial, V: 4.0.0-dev, icon
