### ISSUE TITLE
Excessive link dependencies of ModelicaStandardTables

### ISSUE THREAD

**Issue by rfranke** [modelica/ModelicaStandardLibrary#2785] opened 2018-11-28 09:23 UTC
MSL 3.2.2 introduced additional link dependencies for HDF5 and further dependencies on Z and SZ. This means that even the simplest model using a table needs this library now. This can hardly be considered backwards compatible with MSL 3.2.1 and should be cleaned up in MSL3.2.3.

Take this example:
```
model TableTest
  extends Modelica.Blocks.Tables.CombiTable2D(
      table = [0.0,   1.0,   2.0,   3.0;
               1.0,   1.0,   3.0,   5.0;
               2.0,   2.0,   4.0,   6.0]);
  annotation(uses(Modelica(version="3.2.2")));
end TableTest;
```
Please organize the external libs such that dependecies on HDF5 and recursive dependencies on Z and SZ only arise if a model actually uses these new features. For instance place simple MatIO and new MatIO using HDF5 into separate link objects.

**Comment by beutlich** [comment] 2018-11-28 10:47
> MSL 3.2.2 introduced additional link dependencies for HDF5

This is not the case.

**Comment by rfranke** [comment] 2018-11-28 11:11
And the solution is?

**Comment by dietmarw** [comment] 2018-11-28 11:15
@rfranke 	Since this is not a problem of the MSL but a problem of the tool utilising the MSL (OMC in your case I guess) you need to take it up with the tool not with the MSL.

**Comment by beutlich** [comment] 2018-11-28 12:03
We explicitly do not force HDF5 dependency in MSL. See https://doc.modelica.org/Modelica%203.2.3/Resources/helpOM/Modelica.Blocks.Sources.CombiTimeTable.html:

> The MAT-file format comes in four different versions: v4, v6, v7 and v7.3. The library supports at least v4, v6 and v7 whereas v7.3 is optional.

Optional means, it is tool-specific if v7.3 MAT-files are supported by the tool.

**Comment by HansOlsson** [comment] 2018-11-28 12:11
> Optional means, it is tool-specific if v7.3 MAT-files are supported by the tool.

But one could also consider the case that it is optional based on whether the specific model need them or not. I assume that was the proposal here - but I don't know how to easily achieve that.

**Comment by beutlich** [comment] 2018-11-28 12:32
It is too late for enhancements on MSL 3.2.3. Furthermore, it is not an issue of the C-Sources, but of Modelica.Blocks then.

**Comment by beutlich** [comment] 2018-11-28 12:55
OK, ModelicaStandardTables always links to ModelicaIO, which in turn links to ModelicaMatIO. We would need two different flavours of ModelicaStandardTables then, one that enables reading from file and one that doesn't. Basically, it all already is prepared by means of the macro `NO_FILE_SYSTEM`. Thus, if you build ModelicaStandardTables with `NO_FILE_SYSTEM` you can get rid of the linker dependencies already now.

**Comment by HansOlsson** [comment] 2018-11-28 13:33
> @HansOlsson: one could select the file format in table models -- cf. drop down selectors of File menus known from office programs -- and implement the selection as replaceable model that contains appropriate external function calls and/or annotations.

Ok, it seems that would work - and I could possibly see some similar alternatives.

**Comment by beutlich** [comment] 2018-11-28 15:37
> The optional dependency to zlib is given, whereas hdf5 et al are not mentioned. What is the rationale behind this?

HDF5 was considered as a heavy dependency (in terms of number of files, compile time, object size etc.) compared to zlib considered as light-weight dependency.

**Comment by beutlich** [comment] 2018-11-28 16:14
> The C function `ModelicaIO_readRealTable` looks at the file extension and then either calls `readTxtTable` or `readMatTable`.

For your TableTest model this should not matter since ModelicaIO is not necessary here.

**Comment by beutlich** [comment] 2018-11-28 16:19
Reset labels, milestone and issue title.

**Comment by beutlich** [comment] 2019-08-09 13:24
I did some compile tests in VS2010 of a SimulationX-exported Modelica model consisting of a CombiTimeTable where the table is defined by the model (i.e., not read from file).

| Preprocessor define | File size of executable in bytes |
| :-- | --: |
| `/O1` `/MD` | 522'752 |
| `/O1` `/MD` `/DHAVE_ZLIB=1` | 653'312 |
| `/O1` `/MD` `/DHAVE_ZLIB=1` `/DHAVE_HDF5=1` | 2'583'552 |
| `/O1` `/MD` `/DNO_FILE_SYSTEM` | 371'712 |

As you can see (and reported) avoiding the zlib and hdf5 linking reduces the file size significantly. As a workaround I recommend to not define `HAVE_HDF5` (and possibly also `HAVE_ZLIB`) if your model only utilizes table blocks where the table is defined by the model or by usertab.

The trouble really is by design since the **combi**-tables both implement model- and file-based tables. We could split that combined behaviour in two different implementations but would also need separate library / symbol names for model- and file-based table functions (to avoid name clashes at link time).

The Modelon Base library has a clear separation of table interpolation and file access by means of external objects for table access. This interface separation looks like a proper way for a potential MSL enhancement.

Since these enhancements seem like some major effort which I am unfortunately not able to spend, I am closing the issue as wontfix with the mentioned workaround of the preprocessor defines. If there is some table redesign planned some day (probably as part of #1153), we still might address this issue.

**Closed by beutlich** 2019-08-09 13:24 UTC
Labels: L: Blocks, L: C-Sources, enhancement, wontfix
